# ===================================
# 🐳 DOCKER COMPOSE - LOCAL TESTING
# ===================================
version: '3.8'

services:
  # Application Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chap13_email_app
    ports:
      - "8080:8080"
    environment:
      # Database Configuration
      DB_HOST: 34.9.114.182
      DB_PORT: 3306
      DB_NAME: murach
      DB_USER: root
      DB_PASSWORD: Spk61392005@
      
      # Application Settings
      APP_ENV: development
      LOG_LEVEL: DEBUG
      
      # JVM Options
      JAVA_OPTS: "-Xmx512m -Xms256m -Djava.awt.headless=true"
      CATALINA_OPTS: "-Djava.security.egd=file:/dev/./urandom"
      
      # Connection Pool
      HIKARI_MAX_POOL_SIZE: 5
      HIKARI_MIN_IDLE: 1
      HIKARI_CONNECTION_TIMEOUT: 20000
      HIKARI_IDLE_TIMEOUT: 300000
    
    volumes:
      # Mount logs để xem từ host
      - ./logs:/usr/local/tomcat/logs
    
    networks:
      - app-network
    
    restart: unless-stopped
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  app-network:
    driver: bridge

volumes:
  logs:
    driver: local
